name: 'Auto-Rebase Notify'
author: 'Shahriyar Nasir'
description: 'Automatically notify all PRs to rebase when their base branch receives a new push'
branding:
  icon: 'git-pull-request'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/entrypoint.sh'
