name: Auto-Rebase Notify

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger rebase
        uses: snasirca/autorebase-notify-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
